### ISSUE TITLE
Генерация страницы анкеты по шаблону 

### ISSUE THREAD

**Issue by a1tavista** [a1tavista/mmcs-form#3]
Создать "класс" в Node.JS, который генерирует представление по соответствующему шаблону анкеты, т.е. транслирует некоторый JSON-объект заданного формата в HTML. Формат этого JSON-объекта следующий:

``` json
{
   "feedbackForm": [
      {
         "title": "Насколько полезен с вашей точки зрения данный предмет?",
         "type": "radio",
         "options": [
              "5",
              "4",
              "3",
              "2",
              "1"
         ]
      },
      {
      ...
      }
   ]
}
```

**Comment by axazeano** [comment]
@a1tavista Зачем поле type, если полей другого типа не планируется? И зачем указывать все кнопки, когда можно указать начальное и конечное значение?

**Comment by axazeano** [comment]
Тестовая реализация в коммитах da76af8d77fe6c8204f38732c442b3701edd1eee и 9d1b41b504f6043d0ba10c4ab9271af2a2e72f73
