### ISSUE TITLE
Прописать маршруты в backend'е

### ISSUE THREAD

**Issue by a1tavista** [a1tavista/mmcs-form#4]
Прописать маршруты в Express, которые будут вызывать функции, возвращающие "Hello, world!".

**Comment by andrew-k-21-12** [comment]
/ - титульная страница

/survey - опрос студента
/survey/finish - подтверждение результатов опроса

/maintaining - админ. панель
/maintaining/create - создание анкеты
/maintaining/schedule - управление опросами
/maintaining/results - просмотр результатов опросов
