### ISSUE TITLE
Наладить получение данных от Сервиса БРС

### ISSUE THREAD

**Issue by a1tavista** [a1tavista/mmcs-form#5]
Необходимо получать следующие данные от Сервиса БРС:
1. Список предметов для учебного подразделения
2. Список учебных подразделений
3. Список преподавателей для учебного подразделения

**Comment by andrew-k-21-12** [comment]
На текущий момент нужно заменить участки кода, работающие, как заглушки. Получение данных от БРС необходимо в
- контроллере survey (controllers/survey):
  -- метод getStageDescriptions (неправильная интеграция с БРС)
- контроллер maintaining (controllers/maintaining):
  -- getAllStagesData
  -- getAllBrsDisciplines
  -- getSurveysResults
  -- addStage - во всех перечисленных выше методах данные от БРС не получаются
  -- mergeStageDescriptionsWithBRS - для метода необходимо максимально оптимально реализовать дополнение данных из локальной БД данными БРС
- контроллер brs (controllers/brs): здесь непосредственно осуществляются (пока на уровне заглушек) запросы к БРС

**Comment by andrew-k-21-12** [comment]
UPD: данные о предметах, учителях и группах не должны загружаться каждый раз из БРС, а должны храниться в локальной БД проекта.

Программа минимум: добавить в локальную БД таблицы для хранения предметов, учителей и групп (желательно также обновить seeder'ы и схему для Power Architect - misc/db_project.architect). В указанных в предыдущем комментарии функциях данные теперь должны браться из локальной БД.

Программа максимум: предоставить также веб-интерфейс для удобной загрузки перечисленных сущностей (чтобы не делать это перед запуском проекта вручную в командной строке).

**Comment by andrew-k-21-12** [comment]
Теперь данные хранятся в локальной БД
