### ISSUE TITLE
Наладить механизм авторизации с Сервисом БРС

### ISSUE THREAD

**Issue by a1tavista** [a1tavista/mmcs-form#6]
Авторизация пользователей по логину/почте и паролю и получение данных о роли пользователя (student/teacher/...), ID аккаунта, номера курса и группы для студента. Данная задача подразумевает изменения и в Сервисе БРС.

**Comment by andrew-k-21-12** [comment]
На текущий момент заглушка для авторизации через БРС находится в controllers/brs - метод attemptForStudentsAuth.
Данный метод асинхронный, желательно сохранить формат колбэка, потому что он используется в auth-контроллере.

**Comment by andrew-k-21-12** [comment]
Теперь авторизация реализована через OpenID
